// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Brfs4jMUoAtKVkGBffDPU5dvczw2ELw',
    appId: '1:941865956659:web:c854d1a64b4976a03c7a46',
    messagingSenderId: '941865956659',
    projectId: 'models-tests',
    authDomain: 'models-tests.firebaseapp.com',
    storageBucket: 'models-tests.appspot.com',
    measurementId: 'G-Z243S7654K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACRoolFqjXzh08N6z_rHSjbs-gCPMaV84',
    appId: '1:941865956659:android:5abe76ec0858343d3c7a46',
    messagingSenderId: '941865956659',
    projectId: 'models-tests',
    storageBucket: 'models-tests.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQmtqj_TMGsgNGft9qrrCW99MCV-VZeYU',
    appId: '1:941865956659:ios:c0507c6466ceb1c73c7a46',
    messagingSenderId: '941865956659',
    projectId: 'models-tests',
    storageBucket: 'models-tests.appspot.com',
    iosBundleId: 'com.example.modelsTests1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQmtqj_TMGsgNGft9qrrCW99MCV-VZeYU',
    appId: '1:941865956659:ios:995117f1fb9ecb523c7a46',
    messagingSenderId: '941865956659',
    projectId: 'models-tests',
    storageBucket: 'models-tests.appspot.com',
    iosBundleId: 'com.example.modelsTests1.RunnerTests',
  );
}
